bracketSpacing: true
jsonRecursiveSort: true #https://github.com/Gudahtt/prettier-plugin-sort-json#json-recursive-sort
printWidth: 80
proseWrap: "always"
trailingComma: "all"

overrides:
  - files: ["*.md", "*.yml"]
    options:
      printWidth: 120
