name: "CI Tokenlist"

env:
  ARBITRUM_MAINNET_RPC_URL: "https://arbitrum-mainnet.infura.io/v3/${{ secrets.API_KEY_INFURA }}"
  AVALANCHE_MAINNET_RPC_URL: "https://avalanche-mainnet.infura.io/v3/${{ secrets.API_KEY_INFURA }}"
  BASE_MAINNET_RPC_URL: "https://base-mainnet.infura.io/v3/${{ secrets.API_KEY_INFURA }}"
  BASE_SEPOLIA_RPC_URL: "https://base-sepolia.infura.io/v3/${{ secrets.API_KEY_INFURA }}"
  BLAST_MAINNET_RPC_URL: "https://blast-mainnet.infura.io/v3/${{ secrets.API_KEY_INFURA }}"
  BSC_MAINNET_RPC_URL: "https://bsc-mainnet.infura.io/v3/${{ secrets.API_KEY_INFURA }}"
  ETHEREUM_MAINNET_RPC_URL: "https://mainnet.infura.io/v3/${{ secrets.API_KEY_INFURA }}"
  GNOSIS_MAINNET_RPC_URL: "https://gnosis.drpc.org"
  IOTEX_MAINNET_RPC_URL: "https://rpc.ankr.com/iotex"
  LIGHTLINK_MAINNET_RPC_URL: "https://replicator.phoenix.lightlink.io/rpc/v1"
  LINEA_MAINNET_RPC_URL: "https://linea-mainnet.infura.io/v3/${{ secrets.API_KEY_INFURA }}"
  MODE_MAINNET_RPC_URL: "https://mode.drpc.org"
  MORPH_MAINNET_RPC_URL: "https://rpc-quicknode.morphl2.io"
  OPTIMISM_MAINNET_RPC_URL: "https://optimism-mainnet.infura.io/v3/${{ secrets.API_KEY_INFURA }}"
  POLYGON_MAINNET_RPC_URL: "https://polygon-mainnet.infura.io/v3/${{ secrets.API_KEY_INFURA }}"
  RONIN_MAINNET_RPC_URL: "https://ronin.drpc.org"
  RONIN_TESTNET_RPC_URL: "https://saigon-testnet.roninchain.com/rpc"
  SCROLL_MAINNET_RPC_URL: "https://scroll-mainnet.infura.io/v3/${{ secrets.API_KEY_INFURA }}"
  SEPOLIA_RPC_URL: "https://sepolia.infura.io/v3/${{ secrets.API_KEY_INFURA }}"
  SUPERSEED_MAINNET_RPC_URL: "https://mainnet.superseed.xyz"
  TANGLE_MAINNET_RPC_URL: "https://rpc.tangle.tools"
  ZKSYNC_MAINNET_RPC_URL: "https://zksync-mainnet.infura.io/v3/${{ secrets.API_KEY_INFURA }}"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 3 * * 0" # at 3:00am UTC every Sunday

jobs:
  check-tokenlist:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Check decimals for tokens list"
        run: ./shell/tokenlist.sh
        shell: bash
